name: nzigen_lints
description: Lint rules in mobile developer team in Nzigen Inc. Not only in our company, but also in your team, you can use this lints.
version: 1.0.2

environment:
  sdk: ^3.0.0

dependencies:
  flutter_lints: ^3.0.1

topics:
  - lints

repository: https://github.com/nzigen/nzigen_lints

platforms:
  ios:
  android:
  linux:
  macos:
  windows:
  web: